services:
  sample-book-app-dev:
    build: .
    image: artisktdl/sample-book-app
    container_name: sample-book-app-dev
    ports:
      - 1010:1050
    networks:
      - sample-book-app-compose-netw
  sample-book-app-stg:
    build: .
    image: artisktdl/sample-book-app
    container_name: sample-book-app-stg
    ports:
      - 2020:1050
    networks:
      - sample-book-app-compose-net
  sample-book-app-prd:
    build: .
    image: artisktdl/sample-book-app
    container_name: sample-book-app-prd
    ports:
      - 3030:1050
    networks:
      - sample-book-app-compose-net

networks:
  sample-book-app-compose-net:
    name: sample-book-app-compose-net